services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=danger
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=nestjs
    networks:
      - app-network
networks:
  app-network:
    driver: bridge